name: Get the Eigenlayer operator metadata and upload it to Dune

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Log directory structure
        run: |
          pwd
          ls -R

      - name: pip requirements
        run: pip install -r requirements.txt

      - name: Calculate realized balance daily and upload the data to Dune
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
        run: python -u scripts/get_operator_metadata.py
